jobs:
  00_run_tests:
    if: forgejo.actor != 'baritone'
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format Check
        run: |
          nix fmt -- --ci
      - continue-on-error: true
        name: backups
        run: |
          nix run .#checks.x86_64-linux.backups.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: branding
        run: |
          nix run .#checks.x86_64-linux.branding.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: createusers
        run: |
          nix run .#checks.x86_64-linux.createusers.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: libraries
        run: |
          nix run .#checks.x86_64-linux.libraries.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: migrations
        run: |
          nix run .#checks.x86_64-linux.migrations.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: minimal
        run: |
          nix run .#checks.x86_64-linux.minimal.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: nowizard
        run: |
          nix run .#checks.x86_64-linux.nowizard.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: to_pascal_test
        run: |
          nix run .#checks.x86_64-linux.to_pascal_test.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: verify-examples
        run: |
          nix run .#checks.x86_64-linux.verify-examples.driver
        timeout-minutes: 5
      - continue-on-error: true
        name: xmltests
        run: |
          nix run .#checks.x86_64-linux.xmltests.driver
        timeout-minutes: 5
  01_generate_documentation:
    if: forge.actor != 'baritone' && forge.ref_name == 'main'
    needs: run_tests
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - env:
          SSH_PRIVATE_KEY: $${{ secrets.BARITONE_KEY }}
        name: Generate documentation
        run: |
          nix run .#generate-documentation
          git config --local user.name "baritone"
          git config --local user.email "baritone@mail.spoodythe.one"

          git add documentation/*
          git commit -m "chore: Updated DOCUMENTATION.md" || exit 0

          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key
          git config --local core.sshCommand "ssh -i /tmp/private_key -o StrictHostKeyChecking=no"

          git remote remove origin
          git remote add origin forgejo@git.spoodythe.one:spoody/declarative-jellyfin.git

          git push origin main
name: Actions
"on":
  - push
