jobs:
  02_generate_documentation:
    # if: forge.actor != 'baritone' && forge.ref_name == 'main'
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - env:
          SSH_PRIVATE_KEY: $${{ secrets.BARITONE_KEY }}
        name: Generate documentation
        run: |
          nix run .#generate-documentation
          git config --local user.name "baritone"
          git config --local user.email "baritone@mail.spoodythe.one"

          git add documentation/*
          git commit -m "chore: Updated DOCUMENTATION.md" || exit 0

          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key
          cat /tmp/private_key
          git config --local core.sshCommand "ssh -i /tmp/private_key -o StrictHostKeyChecking=no"

          ssh -i /tmp/private_key -o StrictHostKeyChecking=no forgejo@git.spoodythe.one

name: Actions
"on":
  - push
