name: Run tests

on: [push]

jobs:
  run_tests:
    runs-on: native

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format Check
        run: |
          nix fmt -- --ci
      
      - name: Tests
        run: |
          nix run github:Mic92/nix-fast-build -- --skip-cache --no-nom --no-link -j 2
