name: Run tests

on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/**/*'
      - 'flake.nix'
      - 'flake.lock'
      - 'options/**/*'
      - 'modules/**/*'
      - 'lib/**/*'
      - 'tests/**/*'

jobs:
  run_tests:
    runs-on: native

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: is formatted question mark
        run: |
          nix fmt -- -c *
      
      - name: nix flake check
        run: |
          nix flake check --show-trace --print-build-logs
