name: Run tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: native

    steps:
      - name: Run nix flake check
        uses: actions/checkout@v3
        runs: |
          nix flake check --show-trace
