name: Run tests

on: [push]

jobs:
  run_tests:
    runs-on: native
    if: forge.actor != 'baritone'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format Check
        run: |
          nix fmt -- --ci
      
      - name: Tests
        run: |
          nix run github:Mic92/nix-fast-build -- --skip-cache --no-nom --no-link -j 2

  generate_documentation:
    runs-on: native
    needs: run_tests
    if: forge.actor != 'baritone'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format Check
        run: |
          nix fmt -- --ci
      
      - name: Generate documentation
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BARITONE_KEY }}
        run: |
          nix run .#generate-documentation
          git config --local user.name "baritone"
          git config --local user.email "baritone@mail.spoodythe.one"

          git add DOCUMENTATION.md
          git commit -m "chore: Updated DOCUMENTATION.md"

          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key
          git config --local core.sshCommand "ssh -i /tmp/private_key -o StrictHostKeyChecking=no"

          git remote remove origin
          git remote add origin forgejo@git.spoodythe.one:spoody/declarative-jellyfin.git

          git push origin main
